name: Super-Linter

on: push

jobs:
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Import Secrets
        uses: hashicorp/vault-action
        with:
          url: https://vault-cluster.vault.e97a5cb6-6314-492a-a9ab-7d87e2b4461b.aws.hashicorp.cloud:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci Access_key_ID | AWS_ACCESS_KEY_ID ;
            secret/data/ci Secret_access_key | AWS_SECRET_ACCESS_KEY
