name: Super-Linter

on: push

jobs:
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    env:
      VAULT_ADDR: ${{ secrets.vault_ADDR }}
      VAULT_NAMESPACE: ${{ secrets.VAULT_NAMESPACE }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Installing Vault
        run: |
          sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install vault
          echo
      - run: vault login ${{ secrets.VAULT_TOKEN }}
      - name: Get Access Key
        run:  echo "::set-output name=access-key-id::$(vault kv get --field=ACCESS_KEY_ID kv/ci)"
        id: access-key
      - name: Get Secret Key
        run: echo "::set-output name=secret-access-key::$(vault kv get --field=SECRET_ACCESS_KEY kv/ci)"
        id: secret-key
          echo
   
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault-cluster.vault.e97a5cb6-6314-492a-a9ab-7d87e2b4461b.aws.hashicorp.cloud:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/ci Access_key_ID;
            kv/data/ci Secret_access_key
