name: Super-Linter

on: push

jobs:
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Installing Vault
        run: |
          sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install vault
          echo
      - run:
          export VAULT_ADDR="https://vault-cluster.vault.e97a5cb6-6314-492a-a9ab-7d87e2b4461b.aws.hashicorp.cloud:8200"
          export VAULT_NAMESPACE="admin"
          export VAULT_TOKEN="s.hjPZ09LcubXP8EiP2m3uR3CO.JzvIM"
          echo $VAULT_ADDR
          echo $VAULT_NAMESPACE
          echo $VAULT_TOKEN

      - name: Accessing Secrets
        run: 
          vault login s.hjPZ09LcubXP8EiP2m3uR3CO.JzvIM
          echo
          vault kv get kv/ci
          echo
      
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault-cluster.vault.e97a5cb6-6314-492a-a9ab-7d87e2b4461b.aws.hashicorp.cloud:8200/v1/kv
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci Access_key_ID;
            secret/data/ci Secret_access_key
