name: Super-Linter

on: push

jobs:
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
  build:
    name: vault code
    runs-on: ubuntu-latest
    steps:       
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: http://127.0.0.1:8200
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            secret/ci Access_key_ID;
            secret/ci Secret_access_key
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync . s3://hcvaultbucket
