name: Super-Linter

on: push

jobs:
  super-lint:
    name: lint code base
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://127.0.0.1:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci Access_key_ID
            secret/data/ci Secret_access_key
