name: Super-Linter

on: push

jobs:
  super-lint:
    name: lint code base
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://127.0.0.1:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci Access_key_ID | AWS_ACCESS_KEY_ID;
            secret/data/ci Secret_access_key | AWS_SECRET_ACCESS_KEY
  deploy:
    name: Upload to Amazon S3
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VAULT_TOKEN }}
          aws-secret-access-key: ${{ secrets.VAULT_TOKEN }}
          aws-region: ap-southeast-1
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync . s3://my-s3-test-website-bucket
